[package]
name = "tspressor"
version = "0.1.0"
authors = ["Splamy <splamyn@gmail.com>"]

[lib]
name = "tspressor"
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
lazy_static = "*"
base64 = "0.2"
clipboard = "0.1"
brotli2 = "0.2"
ts3plugin = "0.1"
